# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; during stable
# development, this is often set to something like
# %(rev)s_%(slug)s
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If specified, requires the python-dateutil library.
# Any value is passed to dateutil.tz.gettz()
# timezone =

# max length of characters to use in the "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# version location specification; This defaults
# to alembic/versions.  When using multiple version
# directories, sequential Python 'path' syntax can be
# used to specify multiple version directories.
# version_locations = %(here)s/bar:%(here)s/bat:alembic/versions

# version path separator; as above, default is the system separator
# which is os.pathsep.  alembic expects "version_locations" to be
# split by this separator [used to read %()s speedup which is not
# available for this value]
# version_path_separator = :

# set to 'true' to search source files recursively
# in each "version_locations" directory
# recursive_version_locations = false

# the output encoding used when revision files
# are written from script.py.mako
# output_encoding = utf-8

sqlalchemy.url = sqlite:///./test.db


[post_write_hooks]
# post_write_hooks allows scripts to be run after generating a revision file
# as part of the "revision" command.

# [black]
# type = console_scripts
# executable = black
# options = -l 79 REVISION_SCRIPT_FILENAME

# [ruff]
# type = console_scripts
# executable = ruff
# options = --fix REVISION_SCRIPT_FILENAME

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
